version: "3"
services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
  web: 
    image: snitch:image-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"