# Core
db:
  redis:
    emulate: true
    host: ${REDIS_HOST:-localhost}
    port: 6379
    namespace: EG

cli:
  url: ${CLI_HOST:-http://localhost:9876}

plugins:
  admin:

crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

# OAuth2 Settings
session:
  secret: keyboard cat
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 7200000
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000
