version: "3"
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "${DB_NAME}"
      MONGO_INITDB_ROOT_USERNAME: "${DB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
  web:
    image: snitch:photo-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
